dist: jammy
language: node_js
node_js:
  - 20

jobs:
  include:
    - if: type = push
      script: 
        - npm install -g bump-cli
        - bump deploy docs.yml --doc 273f54d0-b7ae-4ff0-a587-4bd899527bb8 --token $DOC_TOKEN